---
title: "CO2_Flux"
author: "Mégane"
date: "2023-03-20"
output: html_document
---

## Air--Sea CO2 Flux (2007-2018)

```{r libraries, echo=FALSE, warning=FALSE, message=FALSE}
library("readr")
library("viridis")
library("scales")
library("lubridate")
library("gsignal")
library("FactoMineR")
library("factoextra")
library("gplots")
library("heatwaveR")
library("dplyr")
library("imputeTS")
library("Metrics")
library("tidyr")
library("tseries")
library("forecast")
library("tsDyn")
library("tsoutliers")
library("seacarb")
library("lmodel2")
library("lmtest")
library("ggExtra")
library("corrplot")
library("ggcorrplot")
library("LakeMetabolizer")
```

```{r importation data, echo=FALSE, warning=FALSE, message=FALSE}

###Importation des donnees
##Data pCO2 water
#a partir de janvier 2007 jusqu'a janvier 2022

SOMLIT_carbo_chemistry <- read_csv("../Data/data_pH_steeve.csv")

#differenciation surface / 50m

SOMLIT_carbo_chemistry_surf <- SOMLIT_carbo_chemistry %>% 
  dplyr::filter(depth==0) %>% 
  select(sampling_date, salinity, temperature, ta, dic, NO2, NO3, Chla, pH_calc, pCO2) %>% 
  rename(pCO2_water = pCO2) %>% 
  filter(sampling_date <= "2018-12-31") %>% 
  mutate(sampling_date = as.character(sampling_date))
SOMLIT_carbo_chemistry_50m <- SOMLIT_carbo_chemistry %>% 
  dplyr::filter(depth==50)
##

#Data pCO2 air
#pCO2 air (01-avril-1993- 31-12-2018) - daily (ppm)

pCO2_atmos_daily_raw <- read_table("../Data/Atmospheric_CO2_Plateau_Rosa/WDCGG_20230314110158/txt/co2/daily/co2_prs_surface-insitu_64_9999-9999_daily - modif.txt", 
                               col_types = cols(month = col_double(), 
                                                day = col_double(), hour = col_double(), 
                                                minute = col_double(), second = col_double()))


pCO2_atmos_daily_raw <- pCO2_atmos_daily_raw %>% 
  unite(col='datetime', c('year', 'month', 'day'), sep='-') %>% 
  mutate(datetime = format(datetime, format="%Y-%m-%d")) %>% 
  mutate(datetime = as.POSIXct(datetime, format="%Y-%m-%d")) %>% 
  mutate(value = case_when(value == -999.999 ~ NA_real_ , TRUE ~ value)) %>% 
  mutate(value_unc = case_when(value_unc == -999.999 ~ NA_real_ , TRUE ~ value_unc)) %>% 
  rename(pCO2_air = value, SE = value_unc) %>% 
  filter(datetime >= "2007-01-01")


pCO2_atmos <- data.frame(sampling_date = as.character(pCO2_atmos_daily_raw$datetime), pCO2_air = pCO2_atmos_daily_raw$pCO2_air)


DATA <- left_join(SOMLIT_carbo_chemistry_surf, pCO2_atmos, by = as.character("sampling_date"))

```

```{r data wind speed, echo=FALSE, warning=FALSE, message=FALSE}
##Data wind speed (10m)
#importation data wind speed (10m) Azur buoy (1999-2022)
#measured at 3.80 m height, then roughly extrapolated to 10 m by adding 10%
#unity : m/s (1999-2021)
#unity : knot (2022)
#2022 : que le mois de janvier
#observations toutes les heures

Azur_wind_1999 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_1999.dat", 
                             delim = ";", escape_double = FALSE, trim_ws = TRUE)

Azur_wind_2000 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2000.dat", 
                             delim = ";", escape_double = FALSE, trim_ws = TRUE)

Azur_wind_2001 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2001.dat", 
                             delim = ";", escape_double = FALSE, trim_ws = TRUE)

Azur_wind_2002 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2002.dat", 
                             delim = ";", escape_double = FALSE, trim_ws = TRUE)

Azur_wind_2003 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2003.dat", 
                             delim = ";", escape_double = FALSE, trim_ws = TRUE)

Azur_wind_2004 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2004.dat", 
                             delim = ";", escape_double = FALSE, trim_ws = TRUE)

Azur_wind_2005 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2005.dat", 
                             delim = ";", escape_double = FALSE, trim_ws = TRUE)

Azur_wind_2006 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2006.dat", 
                             delim = ";", escape_double = FALSE, trim_ws = TRUE)

Azur_wind_2007 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2007.dat", 
                             delim = ";", escape_double = FALSE, trim_ws = TRUE)

Azur_wind_2008 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2008.dat", 
                             delim = ";", escape_double = FALSE, trim_ws = TRUE)

Azur_wind_2009 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2009.dat", 
                             delim = ";", escape_double = FALSE, trim_ws = TRUE)

Azur_wind_2010 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2010.dat", 
                             delim = ";", escape_double = FALSE, trim_ws = TRUE)

Azur_wind_2011 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2011.dat", 
                             delim = ";", escape_double = FALSE, col_names = FALSE, 
                             trim_ws = TRUE)
Azur_wind_2011 <- Azur_wind_2011 %>% rename(date=X1, `wind speed`=X2)

Azur_wind_2012 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2012.dat", 
                             delim = ";", escape_double = FALSE, col_names = FALSE, 
                             trim_ws = TRUE)
Azur_wind_2012 <- Azur_wind_2012 %>% rename(date=X1, `wind speed`=X2)

Azur_wind_2013 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2013.dat", 
                             delim = ";", escape_double = FALSE, col_names = FALSE, 
                             trim_ws = TRUE)
Azur_wind_2013 <- Azur_wind_2013 %>% rename(date=X1, `wind speed`=X2)

Azur_wind_2014 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2014.dat", 
                             delim = ";", escape_double = FALSE, col_names = FALSE, 
                             trim_ws = TRUE)
Azur_wind_2014 <- Azur_wind_2014 %>% rename(date=X1, `wind speed`=X2)

Azur_wind_2015 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2015.dat", 
                             delim = ";", escape_double = FALSE, col_names = FALSE, 
                             trim_ws = TRUE)
Azur_wind_2015 <- Azur_wind_2015 %>% rename(date=X1, `wind speed`=X2)


Azur_wind_2016 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2016.dat", 
                             delim = ";", escape_double = FALSE, col_names = FALSE, 
                             trim_ws = TRUE)
Azur_wind_2016 <- Azur_wind_2016 %>% rename(date=X1, `wind speed`=X2)

Azur_wind_2017 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2017.dat", 
                             delim = ";", escape_double = FALSE, col_names = FALSE, 
                             trim_ws = TRUE)
Azur_wind_2017 <- Azur_wind_2017 %>% rename(date=X1, `wind speed`=X2)

Azur_wind_2018 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2018.dat", 
                             delim = ";", escape_double = FALSE, col_names = FALSE, 
                             trim_ws = TRUE)
Azur_wind_2018 <- Azur_wind_2018 %>% rename(date=X1, `wind speed`=X2)

Azur_wind_2019 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2019.dat", 
                             delim = ";", escape_double = FALSE, col_names = FALSE, 
                             trim_ws = TRUE)
Azur_wind_2019 <- Azur_wind_2019 %>% rename(date=X1, `wind speed`=X2)

Azur_wind_2020 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FF_2020.dat", 
                             delim = ";", escape_double = FALSE, col_names = FALSE, 
                             trim_ws = TRUE)
Azur_wind_2020 <- Azur_wind_2020 %>% rename(date=X1, `wind speed`=X2)


Azur_wind_2021 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FXI_2021.dat", 
                             delim = ";", escape_double = FALSE, col_names = FALSE, 
                             trim_ws = TRUE)
Azur_wind_2021 <- Azur_wind_2021 %>% rename(date=X1, `wind speed`=X2)

#convert en m/s : 1 knot = 0.514444681 m/s

Azur_wind_2022 <- read_delim("../Data/Wind_speed_10m_Azur_buoy/Azur_FXI_2022.dat", 
                             delim = ";", escape_double = FALSE, col_names = FALSE, 
                             trim_ws = TRUE)
Azur_wind_2022 <- Azur_wind_2022 %>% reframe (date=X1, `wind speed` = case_when(X2 == -9999  ~ NA_real_ , 
                                                                                TRUE ~ (X2*0.514444681)))

#fusion (2007-2018) : Azur_wind_RAW

Azur_wind_RAW <- rbind(Azur_wind_2007, Azur_wind_2008, Azur_wind_2009, Azur_wind_2010,
                       Azur_wind_2011, Azur_wind_2012, Azur_wind_2013, Azur_wind_2014,
                       Azur_wind_2015, Azur_wind_2016, Azur_wind_2016, Azur_wind_2017,
                       Azur_wind_2018)

```

```{r moyenne wind speed par jour, echo=FALSE, warning=FALSE, message=FALSE}
Azur_wind_daily <- Azur_wind_RAW %>% 
  mutate(day = format(date, format="%Y-%m-%d")) %>% 
  group_by(day) %>% 
  mutate(mean_daily = mean(`wind speed`)) %>% 
  reframe(sampling_date=day, wind_mean_daily = mean_daily) %>% 
  select(-day)

Azur_wind_daily <- distinct(Azur_wind_daily)

#integration azur_wind_daily avec DATA

DATA <- left_join(DATA, Azur_wind_daily, by = as.character("sampling_date"))

DATA <- DATA %>% 
  mutate(sampling_date = as.POSIXct(sampling_date))
```

#### Plot pCO2 atmosphere (ppm)

```{r plot pCO2 air (ppm), echo=FALSE, warning=FALSE, message=FALSE}
DATA %>% 
  ggplot() +
  ggtitle("Air pCO2 (ppm) according to time ") +
  aes(x=sampling_date, y=pCO2_air) +
  geom_point()
```

```{r conversion pCO2air en uatm, echo=FALSE, warning=FALSE, message=FALSE}
#pCO2 water en uatm
#pCO2 air en ppm
#convertir les valeurs de pCO2 air en uatm

#package SeaCarb (vapress + p2xCO2)

#vapress : vapeur pressure of seawater in atm

vapress_sw <- vapress(S=DATA$salinity, T=DATA$temperature, form="d2007")

DATA <- DATA %>% 
  mutate(vapress_sw = vapress(S=salinity, T=temperature, form="d2007"))

#pCO2 ppm en pCO2 uatm, formule : xCO2 = pCO2 / (Patm - pH2O)

pCO2_air_uatm <- DATA$pCO2_air * (1-vapress_sw) #Patm en surface = 1

DATA <- DATA %>% 
  mutate(pCO2_air_uatm = pCO2_air * (1-vapress_sw))

##
```

#### Plot pCO2 (uatm)

```{r plot pCO2 air (uatm), echo=FALSE, warning=FALSE, message=FALSE}

DATA %>% 
  ggplot() +
  ggtitle("Air pCO2 (uatm) according to time") +
  aes(x=sampling_date, y=pCO2_air_uatm) +
  geom_point()

```

```{r NpCO2, echo=FALSE, warning=FALSE, message=FALSE}
#calcul de T-normalized pCO2 seawater ou pCO2(N) = non-temperature effects on pCO2water
#formula : pCO2(N) = pCO2w obs * e(0.0423*Tmean-Tobs) = NpCO2 de Kapsenber

#calcul de Tmean :
Tmean <- mean(DATA$temperature, na.rm=T) #18.70

T_norm_pCO2_sw <- DATA %>% 
  dplyr::mutate(T_norm_pCO2_sw = pCO2_water * exp(0.0423*(Tmean-temperature)))

DATA <- DATA %>% 
  dplyr::mutate(T_norm_pCO2_sw = pCO2_water * exp(0.0423*(Tmean-temperature)))

```

#### (pCO2 at Point B : 2007-2018 (Figure 5.a DE CARLO)

```{r Figure 5a DE CARLO, echo=FALSE, warning=FALSE, message=FALSE}
##Figure 5.a DE CARLO :

DATA %>% 
  ggplot() +
  ggtitle("pCO2 at Point B : 2007-2018") +
  geom_line(aes(x=sampling_date, y=pCO2_air_uatm), col='darkgreen') +
  geom_point(aes(x=sampling_date, y=pCO2_water), col='blue', size=0.8) +
  geom_line(aes(x=sampling_date, y=T_norm_pCO2_sw), col='red')

```

#### Annual cycle of pCO2 (2007-2018)

Figure 5.b DE CARLO

```{r Figure 5.b DE CARLO, echo=FALSE, warning=FALSE, message=FALSE}
#annual cycle of pCO2 (2007-2018)

##Figure 5.b DE CARLO :

DATA %>% 
  ggplot() +
  geom_line(aes(x= as.Date(yday(sampling_date), "1970-01-01"), y=pCO2_water, 
                group = factor(year(sampling_date)), 
                color = factor(year(sampling_date))), linewidth = 0.75) +
  scale_colour_viridis_d() +
  scale_x_date(date_breaks="months", date_labels="%b", name = "") +
  labs(x="Months",colour="") +
  theme_bw() +
  scale_y_continuous(name = "pCO2 water (uatm)") 
```

```{r TpCO2, echo=FALSE, warning=FALSE, message=FALSE}
#the effects of only temperature
#calcul de TpCO2 at Tobs
#formula : TpCO2 = pCO2mean * exp[0.0423(Tobs - Tmean)]

#calcul de pCO2mean :
pCO2mean <- mean(DATA$pCO2_water, na.rm=T) #402.03

#calcul de TpCO2 :

TpCO2 <- DATA %>% 
  dplyr::mutate(TpCO2 = pCO2mean * exp(0.0423*(temperature-Tmean)))

DATA <- DATA %>% 
  dplyr::mutate(TpCO2 = pCO2mean * exp(0.0423*(temperature-Tmean)))
##
```

```{r Calcul des deltas, echo=FALSE, warning=FALSE, message=FALSE}
###Calcul des deltas

#calcul delta pCO2(T) = pCO2obs - pCO2(N)
delta_pCO2_T <- DATA$pCO2_water - DATA$T_norm_pCO2_sw

#Calcul pCO2(bio) = pCO2obs - pCO2(T-driven) ou TpCO2
delta_pCO2_bio <- DATA$pCO2_water - DATA$TpCO2

DATA <- DATA %>% 
  dplyr::mutate(delta_pCO2_T = pCO2_water - T_norm_pCO2_sw,
                delta_pCO2_bio = pCO2_water - TpCO2)
##
```

#### Temperature and biological effects on pCO2 variations Plot (Figure 6 DE CARLO)

```{r Figure 6 DE CARLO, echo=FALSE, warning=FALSE, message=FALSE}
#plot
##Figure 6 DE CARLO :

DATA %>% 
  ggplot() + 
  ggtitle("Temperature and biological effects on pCO2 variations") +
  geom_point(aes(x=sampling_date, y=delta_pCO2_T), col='darkgreen', size=0.9) +
  geom_point(aes(x=sampling_date, y=delta_pCO2_bio), col='#EED153', size=0.9)
##

```

```{r Calcul CO2 fluxes, echo=FALSE, warning=FALSE, message=FALSE}
#calcul delta pCO2 (uatm) = pCO2sw - pCO2air

delta_pCO2 <- DATA$pCO2_water - DATA$pCO2_air_uatm
DATA <- DATA %>% mutate(delta_pCO2 = pCO2_water - pCO2_air_uatm)

#calcul du Schmidt number (SC)
#formula : Sc = 2073.1 - (125.62*T) + (3.6276 * T^2) - (0.043219 * T^3)
 Sc <- 2073.1 - (125.62*DATA$temperature) + (3.6276 * DATA$temperature^2) - (0.043219 * DATA$temperature^3)
 DATA <- DATA %>% mutate(Sc = 2073.1 - (125.62*temperature) + (3.6276 * temperature^2) - (0.043219 * temperature^3))

#utilisation de getSchmidt vs Sc article : 
getSchmidt(temperature=25, gas="CO2") #498.8125

2073.1 - (125.62*25) + (3.6276 * 25^2) - (0.043219 * 25^3) #Sc = 524.5531

#calcul de gaz transfert velocity K (m.s-1)
#formula : K = 0.266 * U^2 avec U : wind velocity at 10m

K600 <- 0.266 * DATA$wind_mean_daily^2
DATA <- DATA %>% mutate(K600 = 0.266*wind_mean_daily^2)

#calcul de k (m.s-1)
#formula : k = K * (Sc / 600)^-1/2

#pour que Sc et K600 soient de la mm longueur
k <- K600 * (Sc/600)^(-1/2)
DATA <- DATA %>% mutate(k = K600 * (Sc/600)^(-1/2))

#on part du principe que alpha = 2.912*10^-2 (unity : mmol.m-3.atm)
#calcul de F
#formula : F = k * alpha * deltapCO2

F <- k * (2.912*10^(-2)) * delta_pCO2

DATA <- DATA %>% mutate(Flux_CO2 = k * (2.912*10^(-2)) * delta_pCO2)

```

```{r outliers Flux_CO2, echo=FALSE, warning=FALSE, message=FALSE}

#plot visualiser les outliers
DATA %>% 
  ggplot() +
  aes(x=sampling_date, y=Flux_CO2) +
  geom_boxplot() + 
  xlab(label = "") +
  ylab(label = "") +
  theme(legend.position="none")+
  ggtitle("Flux_CO2 boxplot (outliers)") 

#recuperation des outliers

outliers <- boxplot.stats(DATA$Flux_CO2)
outliers_index <- which(DATA$Flux_CO2 %in% c(outliers$out))

#remplacer les outliers Flux_CO2 par des NA
DATA[DATA$Flux_CO2 %in% outliers$out, "Flux_CO2"] = NA

summary(DATA$Flux_CO2)

```

#### Plot flux CO2 air \~ eau

```{r plot flux CO2 air-eau, echo=FALSE, warning=FALSE, message=FALSE}

DATA %>% 
  ggplot() +
  aes(x=sampling_date, y=Flux_CO2*10^(-3)) +
  geom_point(size=1) + 
  scale_x_datetime(name="") +
  scale_y_continuous(name="Flux (mol C/m²/day)") +
  ggtitle("Days CO2 fluxes ocean-atmosphere")
```
