---
title: "Fusion Data SOMLIT"
author: "Mégane"
date: "2023-04-16"
output: html_document
---


```{r libraries, echo=FALSE, warning=FALSE, message=FALSE}
library("readr")
library("viridis")
library("scales")
library("lubridate")
library("gsignal")
library("FactoMineR")
library("factoextra")
library("gplots")
library("heatwaveR")
library("dplyr")
library("imputeTS")
library("Metrics")
library("tidyr")
library("tseries")
library("forecast")
library("tsDyn")
library("tsoutliers")
library("seacarb")
library("lmodel2")
library("lmtest")
library("ggExtra")
library("corrplot")
library("ggcorrplot")
library("marelac")
library("kableExtra")
library("stringr")

```


### Fusion data SOMLIT :  
  
- data_pH_steeve (data papier Kapsenberg, 09/01/2007 - 11/01/2022, T, S, pH, pCO2, carbonate system...)  
- SOMLIT_HYDRO (pH mesuré du 09/01/2007 - 21/06/2022)  
- SOMLIT_extraction_CTD_dernier (donnees telechargees de SOMLIT, 09/01/2007 - 31/01/2023, donnees manquantes du 13/09/2022 au 03/01/2023, T, S)  
- PtB_data_TS (donne Laura, 11/01/2022 - 30/12/2022, T, S)  
  

```{r importation data brut SOMLIT, echo=FALSE, warning=FALSE, message=FALSE}

SOMLIT_carbo_chemistry <- read_csv("../Data/data_pH_steeve.csv")

SOMLIT_dernier <- read_delim("../Data/Somlit_Extraction_ctd_dernier.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

Data_TS_22 <- read_delim("../Data/PtB_data_TS_2022.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

SOMLIT_hydro <- read_delim("../Data/Somlit_HYDRO.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

```

```{r SOMLIT_dernier : tri, echo=FALSE, warning=FALSE, message=FALSE}

#data surface = mean between 0 and 3 meters
#data 50m = mean between 49 and 51 meters
SOMLIT_dernier <- SOMLIT_dernier %>% 
  filter(between(PROFONDEUR, 49, 51) | PROFONDEUR <=3) %>% 
  mutate(prof = case_when(PROFONDEUR <= 3 ~ "SURF", TRUE ~ "PROF"))

##

#selection year 2021 :
SOMLIT_dernier_surf <- SOMLIT_dernier %>% 
  filter(prof == "SURF") %>% 
  group_by(DATE) %>% 
  mutate(temperature = mean(TEMPERATURE),
         salinity = mean(SALINITE)) %>% 
  select(DATE, temperature, salinity)
SOMLIT_dernier_surf <- distinct(SOMLIT_dernier_surf)

test1 <- SOMLIT_dernier_surf[636:678,]
##
SOMLIT_dernier_prof <- SOMLIT_dernier %>% 
  filter(prof == "PROF") %>% 
  group_by(DATE) %>% 
  mutate(temperature = mean(TEMPERATURE),
         salinity = mean(SALINITE)) %>% 
  select(DATE, temperature, salinity)
SOMLIT_dernier_prof <- distinct(SOMLIT_dernier_prof)

test2 <- SOMLIT_dernier_prof[652:694,]
##

#on retire les dernieres lignes vides :
SOMLIT_carbo_chemistry <- SOMLIT_carbo_chemistry[-c(1513:1528),]


#fusion des 2 (surface & profondeur) a partir de la date souhaitee : 2021-10-25
#2 dates a chaque fois
#premiere ligne = 0m
#deuxieme ligne = 50m
#data au propre : enlever les outliers de salinity, format posixct
test <- rbind(test1, test2)
test <- test %>% arrange(DATE)
test <- test %>% 
  mutate(depth = c("0", "50")) %>% 
  rename(sampling_date = DATE) %>% 
  mutate(sampling_date = format(sampling_date, format = "%Y-%m-%d")) %>% 
  mutate(sampling_date = as.POSIXct(sampling_date, format = "%Y-%m-%d")) %>% 
  mutate(salinity = case_when(salinity > 40 ~ NA_real_, TRUE ~ salinity)) %>% 
  mutate(depth = as.double(depth)) %>% 
  select(sampling_date, depth, salinity, temperature)
##

#preparation a la fusion (sampling_date en character) :
SOMLIT_carbo_chemistry <- SOMLIT_carbo_chemistry %>% 
  mutate(sampling_date = as.character(sampling_date))

test <- test %>% 
  mutate(sampling_date = as.character(sampling_date))

#fusion
essai <- full_join(SOMLIT_carbo_chemistry, test)


```


```{r data TS 22 - tri, echo=FALSE, warning=FALSE, message=FALSE}

#filtration data 1 et 50m
TS_22 <- Data_TS_22 %>% 
  filter(Depth == 1 | Depth == 50) %>% 
  mutate(Date = as.character(Date)) %>%
  mutate(Depth = as.numeric(str_replace(Depth, "1", "0"))) %>% 
  rename(sampling_date = Date, depth = Depth, temperature = T, salinity = S) %>% 
  select(sampling_date, depth, salinity, temperature)


#creation data 2023 a mettre de cote :
data_23 <- essai[c(1589:1598),]

#on retire annee 2022+2023 du dataset :
essai <- essai[-c(1527:1598),]

#on join les data ts 2022 au dataset : 
join <- full_join(essai, TS_22)

#on join les data 2023 au dataset :
join_final <- full_join(join, data_23)


```

```{r enregistrement final, echo=FALSE, warning=FALSE, message=FALSE}


#dataset final : du 09 janvier 2007 au 31 janvier 2023 :
join_final <- join_final %>% 
  mutate(sampling_date = as.POSIXct(sampling_date)) %>% 
  mutate(salinity = case_when(salinity > 40 ~ NA_real_, TRUE ~ salinity),
         temperature = case_when(temperature > 50 ~ NA_real_, TRUE ~ temperature))


#enregistrement nouvelle table csv :

write.table(join_final, "DATA_SOMLIT_07-23.csv", sep=";", col.names = TRUE, row.names = FALSE) 
```

