---
title: "SOMLIT_2022"
author: "Mégane"
date: "2023-04-13"
output: html_document
---


## Importation fichier Somlit_extraction_CTS_dernier.csv  
  
- période : 09/01/2007 jusqu'au 31/01/2023  
- paramètres : salinité + température  
- toutes les profondeurs  
  
Ici on s'intéresse aux données de surface  
  
Le but est de récupérer les données de salinité + température  
  
Les données de pH sont disponibles jusqu'au 21/06/2022

```{r importation dernier fichier SOMLIT CTD, echo=FALSE, warning=FALSE, message=FALSE}

SOMLIT_dernier <- read_delim("../Data/Somlit_Extraction_ctd_dernier.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)

#mean of temperature & salinity (1 to 3m) :
SOMLIT_dernier <- SOMLIT_dernier %>% 
  dplyr::filter(PROFONDEUR <= 3) %>% 
  group_by(DATE) %>% 
  mutate(salinity = mean(SALINITE),
         temperature = mean(TEMPERATURE)) %>% 
  rename(datetime = DATE) %>% 
  select(datetime, temperature, salinity) %>% 
  mutate(datetime=as.character(datetime),
         datetime = as.POSIXct(datetime, format="%Y-%m-%d"))

#tri :
SOMLIT_dernier <- distinct(SOMLIT_dernier)


#enlever les valeurs abbérantes :
SOMLIT_dernier <- SOMLIT_dernier %>% 
  mutate(temperature = case_when(temperature > 99 ~ NA_real_ , TRUE ~ temperature),
         salinity = case_when(salinity > 99 ~ NA_real_ , TRUE ~ salinity),
         salinity = case_when(salinity < 35 ~ NA_real_ , TRUE ~ salinity))



```


## Rajout données pCO~2~ water

```{r importation SOMLIT_carbo (janvier 2022), echo=FALSE, warning=FALSE, message=FALSE}

SOMLIT_carbo <- read_csv("../Data/data_pH_steeve.csv")

#selection data surface :
SOMLIT_carbo <- SOMLIT_carbo %>% 
  dplyr::filter(depth==0) %>% 
  select(sampling_date, salinity, temperature, ta, pH_calc, pCO2) %>% 
  rename(pCO2_w = pCO2, datetime = sampling_date)


test <- SOMLIT_dernier[c(636:673),]

#fusion des 2 datasets :
SOMLIT <- full_join(SOMLIT_carbo, test, by="datetime")

SOMLIT = SOMLIT %>% arrange(datetime)


SOMLIT$salinity.x[is.na(SOMLIT$salinity.x)] <- "NA"
SOMLIT$temperature.x[is.na(SOMLIT$temperature.x)] <- "NA"


SOMLIT <- SOMLIT %>% 
  mutate(salinity.y = as.character(salinity.y),
         temperature.y = as.character(temperature.y)) %>% 
  mutate(salinity = case_when(salinity.x == "NA" ~ salinity.y, TRUE ~ salinity.x),
         temperature = case_when(temperature.x == "NA" ~ temperature.y, TRUE ~ temperature.x)) %>% 
  mutate(salinity = as.numeric(salinity),
         temperature = as.numeric(temperature))
##

SOMLIT <- SOMLIT %>% 
  select(datetime, salinity, temperature, ta, pH_calc, pCO2_w)


summary(SOMLIT)

```


```{r Nombre de mesures SOMLIT par mois, echo=FALSE, warning=FALSE, message=FALSE}

Nb_by_year2 <- summarise(group_by(SOMLIT_dernier, Year), NB_OBS_Y=n()) 

Nb_by_month2 <- summarise(group_by(SOMLIT_dernier, Year.Month), NB_OBS_M=n()) 

Nb_by_month2 <- Nb_by_month2 %>% 
  mutate(Year.Month = as.Date(paste(Year.Month, "-01", sep = ""), format = "%Y-%m-%d"))


#plot number of measure by month (2077-2022)
Nb_by_month2 %>% 
  ggplot() +
  aes(x=Year.Month, y=NB_OBS_M) +
  geom_line(group=1) + 
  scale_x_date(name="") + 
  scale_y_continuous(name="") +
  ggtitle("Number of observations by month at Point P (2007-2022)")
  


```



